set_property PACKAGE_PIN AK20 [get_ports TX_ACK_WEST]
set_property IOSTANDARD LVCMOS25 [get_ports TX_ACK_WEST]
set_property PACKAGE_PIN AJ20 [get_ports TX_REQ_WEST]
set_property IOSTANDARD LVCMOS25 [get_ports TX_REQ_WEST]
set_property PACKAGE_PIN AF24 [get_ports {TX_DATA_WEST[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TX_DATA_WEST[0]}]
set_property PACKAGE_PIN AF23 [get_ports {TX_DATA_WEST[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TX_DATA_WEST[1]}]
set_property PACKAGE_PIN AF20 [get_ports {TX_DATA_WEST[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TX_DATA_WEST[2]}]
set_property PACKAGE_PIN AG20 [get_ports {TX_DATA_WEST[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TX_DATA_WEST[3]}]
set_property PACKAGE_PIN AF22 [get_ports {TX_DATA_WEST[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TX_DATA_WEST[4]}]
set_property PACKAGE_PIN AE22 [get_ports {TX_DATA_WEST[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TX_DATA_WEST[5]}]
set_property PACKAGE_PIN AJ23 [get_ports {TX_DATA_WEST[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TX_DATA_WEST[6]}]
set_property PACKAGE_PIN AJ24 [get_ports {TX_DATA_WEST[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TX_DATA_WEST[7]}]
set_property PACKAGE_PIN AD24 [get_ports {TX_DATA_WEST[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TX_DATA_WEST[8]}]
set_property PACKAGE_PIN AC24 [get_ports {TX_DATA_WEST[9]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TX_DATA_WEST[9]}]
set_property PACKAGE_PIN AK18 [get_ports {TX_DATA_WEST[10]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TX_DATA_WEST[10]}]
set_property PACKAGE_PIN AK17 [get_ports {TX_DATA_WEST[11]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TX_DATA_WEST[11]}]
set_property PACKAGE_PIN V23 [get_ports {TX_DATA_WEST[12]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TX_DATA_WEST[12]}]
set_property PACKAGE_PIN W24 [get_ports {TX_DATA_WEST[13]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TX_DATA_WEST[13]}]
set_property PACKAGE_PIN AB24 [get_ports {TX_DATA_WEST[14]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TX_DATA_WEST[14]}]
set_property PACKAGE_PIN AA24 [get_ports {TX_DATA_WEST[15]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TX_DATA_WEST[15]}]


set_property PACKAGE_PIN AG19 [get_ports RX_ACK_WEST]
set_property IOSTANDARD LVCMOS25 [get_ports RX_ACK_WEST]
set_property PACKAGE_PIN AF19 [get_ports RX_REQ_WEST]
set_property IOSTANDARD LVCMOS25 [get_ports RX_REQ_WEST]
set_property PACKAGE_PIN AE21 [get_ports {RX_DATA_WEST[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RX_DATA_WEST[0]}]
set_property PACKAGE_PIN AD21 [get_ports {RX_DATA_WEST[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RX_DATA_WEST[1]}]
set_property PACKAGE_PIN U26 [get_ports {RX_DATA_WEST[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RX_DATA_WEST[2]}]
set_property PACKAGE_PIN U27 [get_ports {RX_DATA_WEST[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RX_DATA_WEST[3]}]
set_property PACKAGE_PIN AG21 [get_ports {RX_DATA_WEST[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RX_DATA_WEST[4]}]
set_property PACKAGE_PIN AH21 [get_ports {RX_DATA_WEST[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RX_DATA_WEST[5]}]
set_property PACKAGE_PIN AH23 [get_ports {RX_DATA_WEST[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RX_DATA_WEST[6]}]
set_property PACKAGE_PIN AH24 [get_ports {RX_DATA_WEST[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RX_DATA_WEST[7]}]
set_property PACKAGE_PIN AA23 [get_ports {RX_DATA_WEST[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RX_DATA_WEST[8]}]
set_property PACKAGE_PIN AA22 [get_ports {RX_DATA_WEST[9]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RX_DATA_WEST[9]}]
set_property PACKAGE_PIN AG24 [get_ports {RX_DATA_WEST[10]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RX_DATA_WEST[10]}]
set_property PACKAGE_PIN AG25 [get_ports {RX_DATA_WEST[11]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RX_DATA_WEST[11]}]
set_property PACKAGE_PIN AH22 [get_ports {RX_DATA_WEST[12]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RX_DATA_WEST[12]}]
set_property PACKAGE_PIN AG22 [get_ports {RX_DATA_WEST[13]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RX_DATA_WEST[13]}]
set_property PACKAGE_PIN AH19 [get_ports {RX_DATA_WEST[14]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RX_DATA_WEST[14]}]
set_property PACKAGE_PIN AJ19 [get_ports {RX_DATA_WEST[15]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RX_DATA_WEST[15]}]


#led_left
set_property PACKAGE_PIN Y21 [get_ports EMIO_tri_io[0]]
set_property IOSTANDARD LVCMOS25 [get_ports EMIO_tri_io[0]]
#led_right 
set_property PACKAGE_PIN W21 [get_ports EMIO_tri_io[1] ]
set_property IOSTANDARD LVCMOS25 [get_ports EMIO_tri_io[1] ]
#PMOD1_1_LS RESET
set_property PACKAGE_PIN AK21 [get_ports EMIO_tri_io[2]]
set_property IOSTANDARD LVCMOS25 [get_ports EMIO_tri_io[2]]
#PMOD1_2_LS TIK
set_property PACKAGE_PIN AB21 [get_ports EMIO_tri_io[3]]
set_property IOSTANDARD LVCMOS25 [get_ports EMIO_tri_io[3]]